### ISSUE TITLE
× TypeError: Cannot assign to read only property 'parent' of object '#<Object>' : v19

### ISSUE THREAD

**Issue by throne1986** [prevwong/craft.js#288] opened 2021-07-28 19:52 UTC
I am trying to refactor the landing page example using pure react without typescript.
But I am getting the following error: `×
TypeError: Cannot assign to read only property 'parent' of object '#<Object>'`

![image](https://user-images.githubusercontent.com/27904724/127386767-73021023-090b-4f6b-afa9-a48fdd06efd9.png)

Here is my repo:  [https://github.com/throne1986/landing-app](url)

What is wrong here?

**Comment by throne1986** [comment] 2021-07-29 08:32
@zaki-yama, @prevwong  when I commented children in `Container /index.js` the error is gone, 
can you check what is wrong here, I am out of the idea 
![image](https://user-images.githubusercontent.com/27904724/127459135-5d3557cb-6771-4a87-8de4-e6e52f0158cd.png)

**Comment by ankri** [comment] 2021-07-29 14:36
Your [Editor](https://github.com/throne1986/landing-app/blob/master/src/App.js#L10) doesn't have any resolvers

**Comment by throne1986** [comment] 2021-07-29 17:36
> Your [Editor](https://github.com/throne1986/landing-app/blob/master/src/App.js#L10) doesn't have any resolvers. This may not be _the_ problem but definitely is _a_ problem.
> 
> Edit:
> Just saw your second resolver in `pages/index.tsx`. I recommend only using one Editor. Also, the problem is somewhere in your Custom1-Custom3 components. It works as soon I comment them out
> 
> Edit2:
> It's the `<Element />`s inside the Custom components. Currently, I cannot figure out why they would fail.

ur right it works as u suggested

**Comment by throne1986** [comment] 2021-07-29 20:24
> Your [Editor](https://github.com/throne1986/landing-app/blob/master/src/App.js#L10) doesn't have any resolvers. Which may not be _the_ problem but definitely is _a_ problem.
> 
> Edit:
> Just saw your second resolver in `pages/index.tsx`. I recommend only using one Editor. Also the problem is somewhere in your Custom1-Custom3 components. It works as soon I comment them out
> 
> Edit2:
> It's the `<Element />`s inside the Custom components. Currently, I cannot figure out why they would fail.

I hope someone can create a pure react demo for the landing page which is working

**Comment by prevwong** [comment] 2021-08-02 08:11
Duplicate of #255

**Closed by prevwong** 2021-08-02 08:11 UTC
